AWSTemplateFormatVersion: '2010-09-09'
Description: 'ContribConnect - S3 Buckets for raw data, Knowledge Base docs, and web hosting'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # Raw Data Bucket
  RawDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cc-raw-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToGlacierAfter90Days
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
      Tags:
        - Key: Project
          Value: ContribConnect
        - Key: Environment
          Value: !Ref Environment

  # Knowledge Base Documents Bucket
  KnowledgeBaseDocsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cc-kb-docs-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: ContribConnect
        - Key: Environment
          Value: !Ref Environment

  # Web Hosting Bucket
  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'cc-web-${Environment}-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Project
          Value: ContribConnect
        - Key: Environment
          Value: !Ref Environment

  # Bucket Policy for Web Bucket (CloudFront OAC access)
  WebBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub '${WebBucket.Arn}/*'
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref AWS::AccountId

Outputs:
  RawDataBucketName:
    Description: Name of the Raw Data bucket
    Value: !Ref RawDataBucket
    Export:
      Name: !Sub '${AWS::StackName}-RawDataBucket'

  KnowledgeBaseDocsBucketName:
    Description: Name of the Knowledge Base Docs bucket
    Value: !Ref KnowledgeBaseDocsBucket
    Export:
      Name: !Sub '${AWS::StackName}-KnowledgeBaseDocsBucket'

  WebBucketName:
    Description: Name of the Web bucket
    Value: !Ref WebBucket
    Export:
      Name: !Sub '${AWS::StackName}-WebBucket'

  WebBucketArn:
    Description: ARN of the Web bucket
    Value: !GetAtt WebBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-WebBucketArn'
